# Generated by Django 5.0.4 on 2024-08-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
